$bytes = [System.IO.File]::ReadAllBytes('apply_comments_phase4.ps1')
$bom = [byte[]](239,187,191)
$out = new-object byte[] ($bom.Length + $bytes.Length)
$bom.CopyTo($out, 0)
$bytes.CopyTo($out, $bom.Length)
[System.IO.File]::WriteAllBytes('apply_comments_phase4_bom.ps1', $out)
